import os
import sys
import glob
import json
from src.core.bot_runner import BotRunner

# --- Constants ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SAVE_DIR = os.path.join(BASE_DIR, "saved_details")

def main():
    """
    Main function to find the booking config and run the bot.
    It now looks for a specific 'config.json' file.
    """
    print("--- IRCTC Bot Backend ---")

    # Add src to python path to allow for absolute imports
    sys.path.insert(0, os.path.join(BASE_DIR, 'src'))

    # The bot now uses a single, consistent config file generated by the UI.
    config_file = os.path.join(SAVE_DIR, 'config.json')

    if not os.path.exists(config_file):
        print(f"Error: Configuration file not found at '{config_file}'.")
        print("Please click 'Start BOT' in the UI to generate it.")
        sys.exit(1)

    print(f"[*] Using configuration from: {os.path.basename(config_file)}")

    with open(config_file, 'r', encoding='utf-8') as f:
        config = json.load(f)

    try:
        runner = BotRunner(config)
        runner.start()
        print("[*] Bot run finished.")
    except Exception as e:
        print(f"\n[FATAL] An unexpected error occurred: {e}")
        sys.exit(1)
    finally:
        print("[*] Script finished.")

if __name__ == "__main__":
    main()
