AADHAAR_OK_BUTTON = "button.btn-primary[aria-label*='Aadhaar authenticated users']"
DISHA_BANNER_CLOSE_BUTTON = "img#disha-banner-close"
# --- Login Page Selectors ---
LOGIN_BUTTON_HOME = "//a[contains(@class, 'loginText')]"
USERNAME_INPUT = "input[formcontrolname='userid']"
PASSWORD_INPUT = "input[formcontrolname='password']"
CAPTCHA_IMAGE_LOGIN = "img.captcha-img"
CAPTCHA_INPUT_LOGIN = "input[formcontrolname='captcha']"
CAPTCHA_REFRESH_BUTTON = "span.glyphicon-repeat"
SIGN_IN_BUTTON_MODAL = "button.search_btn.train_Search.train_Search_custom_hover"
LOGOUT_BUTTON = "a[aria-label='logout']"
JOURNEY_FROM_INPUT = "p-autocomplete[formcontrolname='jps-origin'] input"
JOURNEY_TO_INPUT = "p-autocomplete[formcontrolname='jps-destination'] input"
DATE_INPUT = "p-calendar[formcontrolname='jps-journey-date'] input"
FIND_TRAINS_BUTTON = "button.train_Search"
AUTOCOMPLETE_OPTION = "li[role='option']"
TRAIN_LIST_ITEM = "div.p-slidetab-content"
QUOTA_TATKAL_RADIO = "p-radiobutton[id='tatkal']"
CLASS_SELECTOR_TEMPLATE = "td[class*='{class_code}']"
BOOK_NOW_BUTTON = "button.btnDefault.train_Search"
PASSENGER_NAME_INPUT = "p-autocomplete[formcontrolname='passengerName'] input"
PASSENGER_AGE_INPUT = "input[formcontrolname='passengerAge']"
PASSENGER_GENDER_DROPDOWN = "p-dropdown[formcontrolname='passengerGender']"
GENDER_OPTION_XPATH = "//span[contains(text(),'{gender}')]"
PASSENGER_PREFERENCE_DROPDOWN = "p-dropdown[formcontrolname='passengerBerthChoice']"
BERTH_OPTION_XPATH = "//span[contains(text(),'{berth}')]"
ADD_PASSENGER_BUTTON = "button.psgn-smry-btn"
PASSENGER_MOBILE_INPUT = "input[formcontrolname='mobileNumber']"
SUBMIT_PASSENGER_DETAILS_BUTTON = "button.train_Search.continue-booking-btn"
CAPTCHA_INPUT_REVIEW = "input[formcontrolname='nlpAnswer']"
CAPTCHA_IMAGE_REVIEW = "img.captcha-img"
PROCEED_TO_PAY_BUTTON = "button.train_Search.payment-button"
PAYMENT_METHOD_UPI_RADIO_XPATH = "//div[contains(text(), 'BHIM/ UPI')]/ancestor::div[1]/preceding-sibling::div/p-radiobutton"
PAY_AND_BOOK_BUTTON = "button.btn.btn-primary.btn-lg"
PNR_CONFIRMATION_POPUP = "div.p-dialog-content"
SPINNER_OVERLAY = "div.pre-load-new"
